name: ploton
version: '1.0.0.0'
synopsis: A useful cli tool to draw figures
description: Please see README.md
category: CLI
author: ishiy
maintainer: y.ishihara.1993@gmail.com
copyright: 2017 ishiy1993
license: BSD3
github: ishiy1993/ploton
extra-source-files:
- README.md

library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
  - optparse-applicative
  - process
  - split
  - transformers

executables:
  ploton:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ploton

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ploton
    - hspec
